#!/usr/bin/env python3
"""Emit a pgfplots figure (recall@10 vs distances/query, SIFT and GloVe) from the result logs.

usage: python3 bench/plot_pareto.py <results-dir> > pareto.tex   (kept at the top level of the manuscript directory and pulled in with \input{pareto})

Series and their sources (all in graft-ann/results):
  SIFT  GRAFT   e7_sift_tsweep.log   RUN sift_T16_ef400   (fast profile T16/ef400)
  SIFT  Vamana  e7_sift_baselines.log  block 'VAMANA sift'  ('average cmps' lines)
  SIFT  PiPNN   e7_sift_baselines.log  block 'PIPNN sift'
  SIFT  hnswlib e12_hnsw_ladder.log    RUN hnsw_sift_M16
  GloVe GRAFT   e4/harvest_sweep3.log  RUN h600c64          (quality profile T32/ef600)
  GloVe Vamana  e1/vamana_hcnng.log    first Vamana sweep (R100 L200)
  GloVe PiPNN   e1/pipnn_full_r1.log
  GloVe hnswlib four points transcribed from the E1 summary (raw sweep not retained)
"""
import re, sys, os
R = sys.argv[1]

def graft_run(path, run):
    out, on = [], False
    for ln in open(os.path.join(R, 'results', path)):
        if ln.startswith('### RUN ' + run): on = True; continue
        if on and ln.startswith('### END'): break
        if on:
            m = re.match(r'\s+(\d+)\s+(0\.\d+)\s+(\d+)\s', ln)
            if m: out.append((int(m.group(3)), float(m.group(2))))
    assert out, (path, run)
    return out

def parlay_block(path, start_pat, end_pat=None):
    out, on = [], start_pat is None
    for ln in open(os.path.join(R, 'results', path)):
        if start_pat and start_pat in ln: on = True; out = []; continue
        if on and end_pat and end_pat in ln: break
        if on:
            m = re.search(r'recall = ([0-9.]+).*average cmps = (\d+)', ln)
            if m: out.append((int(m.group(2)), float(m.group(1))))
    assert out, (path, start_pat)
    return out

S = {
 'sift': {
  'GRAFT (T16)':   graft_run('e7_sift_tsweep.log', 'sift_T16_ef400'),
  'Vamana':        parlay_block('e7_sift_baselines.log', '=== VAMANA sift', '=== PIPNN'),
  'PiPNN':         parlay_block('e7_sift_baselines.log', '=== PIPNN sift'),
  'hnswlib (M16)': graft_run('e12_hnsw_ladder.log', 'hnsw_sift_M16'),
 },
 'glove': {
  'GRAFT (T32)':   graft_run('e4/harvest_sweep3.log', 'h600c64'),
  'Vamana':        parlay_block('e1/vamana_hcnng.log', 'Vamana graph built', 'HCNNG'),
  'PiPNN':         parlay_block('e1/pipnn_full_r1.log', None),
  'hnswlib (M48)': [(16050, 0.951), (23616, 0.970), (45500, 0.986), (65355, 0.993)],
 },
}
style = {
 'GRAFT':   'color=black, mark=*, thick',
 'Vamana':  'color=blue!70!black, mark=square*, densely dashed',
 'PiPNN':   'color=red!70!black, mark=triangle*, densely dotted',
 'hnswlib': 'color=green!50!black, mark=o, dash dot',
}
def panel(key, title, xmin, xmax, xtick, ylabel):
    print(r'\nextgroupplot[title={%s}, xmin=%d, xmax=%d, xtick={%s}%s]' % (title, xmin, xmax, xtick, ylabel))
    for name, pts in S[key].items():
        st = style[name.split()[0]]
        print(r'\addplot[%s] coordinates {' % st)
        print('  ' + ' '.join('(%d,%.4f)' % p for p in pts if p[1] >= 0.84))
        print('};')
        print(r'\addlegendentry{%s}' % name)
print(r'''% generated by bench/plot_pareto.py from the result logs; do not edit by hand
\begin{tikzpicture}
\begin{groupplot}[group style={group size=2 by 1, horizontal sep=0.9cm},
  width=0.5\linewidth, height=5.8cm, xmode=log, ymin=0.85, ymax=1.0, ytick={0.85,0.9,0.95,1.0}, log ticks with fixed point,
  xlabel={distances / query}, grid=major, grid style={black!12},
  tick label style={font=\scriptsize}, label style={font=\footnotesize},
  title style={font=\footnotesize}, legend style={font=\scriptsize, at={(0.97,0.03)}, anchor=south east, draw=black!30, fill=white},
  legend cell align=left, every axis plot/.append style={line width=0.7pt, mark size=1.6pt},
  extra y ticks={0.95,0.97}, extra y tick labels={}, extra y tick style={grid=major, grid style={black!45, densely dashed}}]''')
panel('sift', r'SIFT ($10^6 \times 128$)', 700, 8000, '1000,2000,4000,8000', ', ylabel={recall@10}')
panel('glove', r'GloVe ($1.18\cdot 10^6 \times 100$)', 2500, 80000, '5000,10000,20000,40000,80000', '')
print(r'''\end{groupplot}
\end{tikzpicture}''')
